export default {
  // game
  START_GAME: 'START_GAME',
  INIT_SURVEY: 'INIT_SURVEY',
  GET_RESULTS: 'GET_RESULTS',
  CONTINUE_GAME: 'CONTINUE_GAME',
  INCREMENT_SCORE: 'INCREMENT_SCORE',
  GAME_OVER: 'GAME_OVER',
  RESET_SCORE: 'RESET_SCORE',
};